package(
    default_visibility = [
        "//visibility:public",
    ],
)


load("//build/bazel_mgk_rules:mgk.bzl", "define_mgk")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")

mgk_kmi_symbol_list = "//kernel-6.6:android/abi_gki_aarch64_mtk"

filegroup(
        name = "mgk_configs",
        srcs = glob([
            "arch/arm64/configs/*",
            "kernel/configs/**",
            "**/Kconfig",
            "drivers/cpufreq/Kconfig.*",
        ]) + [
            "Kconfig.ext",
            # FIXME
            "Makefile.ext",
            "certs/mtk_signing_key.pem",
            "//kernel_device_modules-6.6/drivers/dma-buf/heaps:Kconfig",
            "//kernel_device_modules-6.6/drivers/gpu/drm/mediatek/mediatek_v2:Kconfig",
            "//kernel_device_modules-6.6/drivers/gpu/drm/mediatek/mediatek_v2:mtk_drm_edp/Kconfig",
            "//kernel_device_modules-6.6/drivers/gpu/drm/mediatek/mml:Kconfig",
            "//kernel_device_modules-6.6/drivers/memory/mediatek:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/btif:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/mtk-interconnect:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/conn_md:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/conn_scp:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/connectivity:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/eccci:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/geniezone:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/geniezone:gz-trusty/Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/mcupm:Kconfig",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/tinysys_scmi:Kconfig",
        ],
)
filegroup(
        name = "mgk_dt-bindings",
        srcs = glob([
            "include/dt-bindings/**",
            "include/dtc/**",
        ]),
)

filegroup(
        name = "mgk_subpackage_sources",
        srcs = [
            "//kernel_device_modules-6.6/drivers/dma-buf/heaps:sources",
            "//kernel_device_modules-6.6/drivers/gpu/drm/mediatek/mediatek_v2:sources",
            "//kernel_device_modules-6.6/drivers/gpu/drm/mediatek/mml:sources",
            "//kernel_device_modules-6.6/drivers/gpu/drm/mediatek/mtk_sync:sources",
            "//kernel_device_modules-6.6/drivers/gpu/mediatek/gpueb:sources",
            "//kernel_device_modules-6.6/drivers/gpu/mediatek/mt-plat:sources",
            "//kernel_device_modules-6.6/drivers/memory/mediatek:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/aee/aed:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/aee/mrdump:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/btif:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/conn_md:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/conn_scp:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/connectivity:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/cmdq/mailbox:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/eccci:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/geniezone:sources",
            "//kernel_device_modules-6.6/drivers/iommu/arm/arm-smmu-v3:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/mbraink/bridge:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/mcupm:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/mcupm/v2:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/mme/src:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/mmp/src:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/mtk-interconnect:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/sspm/v3:sources",
            "//kernel_device_modules-6.6/drivers/misc/mediatek/tinysys_scmi:sources",
        ],
)

ddk_headers(
        name = "headers",
        hdrs = glob([
            "arch/arm64/include/**/*.h",
            "drivers/misc/mediatek/include/**/*.h",
            "include/**/*.h",
        ]),
        includes = [
            "arch/arm64/include",
            "drivers/misc/mediatek/include",
            "drivers/misc/mediatek/include/mt-plat",
            "include",
        ],
)

# mgk_64_k66
load("//kernel_device_modules-6.6:kernel/kleaf/mgk_64.bzl",
     "mgk_64_defconfig",
     "mgk_64_kleaf_modules",
     "mgk_64_kleaf_eng_modules",
     "mgk_64_kleaf_userdebug_modules",
     "mgk_64_kleaf_user_modules",
     "mgk_64_common_modules",
     "mgk_64_common_eng_modules",
     "mgk_64_common_userdebug_modules",
     "mgk_64_common_user_modules",
     "mgk_64_device_modules",
     "mgk_64_platform_device_modules",
     "mgk_64_device_eng_modules",
     "mgk_64_platform_device_eng_modules",
     "mgk_64_device_userdebug_modules",
     "mgk_64_platform_device_userdebug_modules",
     "mgk_64_device_user_modules",
     "mgk_64_platform_device_user_modules"
)


# FIRE 6.6 local extra device module outs
_fire_extra_module_outs = [
    "drivers/dma-buf/heaps/mtk_heap_debug.ko",
    "drivers/dma-buf/heaps/mtk_heap_refill.ko",
    "drivers/dma-buf/heaps/mtk_sec_heap.ko",
    "drivers/dma-buf/heaps/system_heap.ko",
    "drivers/gpu/drm/mediatek/mtk_sync/mtk_sync.ko",
    "drivers/power/supply/syv690.ko",
]

define_mgk(
    name = "mgk_64_k66",
    defconfig = mgk_64_defconfig,
    kleaf_modules = mgk_64_kleaf_modules,
    kleaf_eng_modules = mgk_64_kleaf_eng_modules,
    kleaf_userdebug_modules = mgk_64_kleaf_userdebug_modules,
    kleaf_user_modules = mgk_64_kleaf_user_modules,
    common_modules = mgk_64_common_modules,
    common_eng_modules = mgk_64_common_eng_modules,
    common_userdebug_modules = mgk_64_common_userdebug_modules,
    common_user_modules = mgk_64_common_user_modules,
    device_modules = mgk_64_device_modules + _fire_extra_module_outs,
    platform_device_modules = mgk_64_platform_device_modules,
    device_eng_modules = mgk_64_device_eng_modules,
    platform_device_eng_modules = mgk_64_platform_device_eng_modules,
    device_userdebug_modules = mgk_64_device_userdebug_modules,
    platform_device_userdebug_modules = mgk_64_platform_device_userdebug_modules,
    device_user_modules = mgk_64_device_user_modules,
    platform_device_user_modules = mgk_64_platform_device_user_modules,
    symbol_list = mgk_kmi_symbol_list,
)
