load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

exports_files([
    "Kconfig",
])

filegroup(
    name = "sources",
    srcs = glob([
        "**",
    ], exclude = [
        "BUILD.bazel",
    ]),
)

ddk_headers(
    name = "conn_md_headers",
    hdrs = glob([
        "include/**/*.h",
    ]),
    includes = [
        "include",
    ],
)

define_mgk_ko(
    name = "conn_md_drv",
)
