load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

exports_files([
    "Kconfig",
])

filegroup(
    name = "sources",
    srcs = glob([
        "**",
    ], exclude = [
        "BUILD.bazel",
        "flash/BUILD.bazel",
    ]),
)

define_mgk_ko(
    name = "leds-mtk",
)

define_mgk_ko(
    name = "leds-mtk-pwm",
)

define_mgk_ko(
    name = "leds-mtk-disp",
)

define_mgk_ko(
    name = "regulator-vibrator",
)
