load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

exports_files([
    "Kconfig",
])

filegroup(
    name = "sources",
    srcs = glob([
        "**",
    ], exclude = [
        "BUILD.bazel",
    ]),
)

ddk_headers(
    name = "btif_common_headers",
    hdrs = glob([
        "common/inc/**/*.h",
    ]),
    includes = [
        "common/inc",
    ],
)

define_mgk_ko(
    name = "btif_drv",
    outs = [
        "common/btif_drv.ko",
    ],
)
